In [1]:
import torch
print(torch.__version__)
print(torch.cuda.is_available())
print(torch.version.cuda)

2.6.0+cu124
False
12.4


## Creating a Tensor

In [2]:
a = torch.empty(size=(2,3)) #allocates memory and shows what is stored at that location

In [3]:
type(a)

torch.Tensor

In [4]:
torch.zeros(3,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [5]:
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [6]:
torch.rand(2,3)

tensor([[0.5047, 0.8647, 0.6636],
        [0.2055, 0.3779, 0.2899]])

In [7]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [8]:
torch.tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

## Tensor Shapes

In [9]:
x = torch.tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [10]:
x.shape

torch.Size([3, 3])

In [11]:
y = torch.empty_like(x)

In [12]:
y

tensor([[2.1707e-18, 7.0952e+22, 1.7748e+28],
        [1.8176e+31, 7.2708e+31, 5.0778e+31],
        [3.2608e-12, 1.7728e+28, 7.0367e+22]])

## Tensor Datatype

In [13]:
x.dtype

torch.float32

In [14]:
x.to(int)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

## Mathematical Operations

In [15]:
x+2

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])

In [16]:
x+y

tensor([[2.1707e-18, 7.0952e+22, 1.7748e+28],
        [1.8176e+31, 7.2708e+31, 5.0778e+31],
        [3.2608e-12, 1.7728e+28, 7.0367e+22]])

In [17]:
 torch.sum(x+y)

tensor(1.4170e+32)

In [18]:
x>y

tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])

## Inplace operations

In [19]:
x.add_(y)

tensor([[2.1707e-18, 7.0952e+22, 1.7748e+28],
        [1.8176e+31, 7.2708e+31, 5.0778e+31],
        [3.2608e-12, 1.7728e+28, 7.0367e+22]])

In [20]:
x

tensor([[2.1707e-18, 7.0952e+22, 1.7748e+28],
        [1.8176e+31, 7.2708e+31, 5.0778e+31],
        [3.2608e-12, 1.7728e+28, 7.0367e+22]])

In [21]:
id(x)

133693172637072

In [22]:
id(y)

133693172635536

In [23]:
z=x

In [24]:
id(z)

133693172637072

In [25]:
z=x.clone()

In [26]:
id(z)

133693173303632

## GPU Operations

In [27]:
torch.cuda.is_available()

False

In [28]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

In [29]:
torch.rand(20,30,device=device)

tensor([[2.6269e-01, 4.2840e-02, 2.0803e-01, 1.1804e-01, 1.2169e-01, 7.3560e-01,
         7.1177e-01, 7.8758e-01, 4.1831e-01, 9.0141e-01, 9.9689e-01, 7.5651e-01,
         2.2389e-01, 3.0235e-01, 1.7842e-01, 8.2384e-01, 5.5574e-01, 9.7702e-01,
         4.4402e-01, 9.4785e-01, 7.4448e-01, 4.8920e-01, 2.4256e-01, 7.0034e-01,
         5.2769e-01, 2.4718e-01, 7.9089e-01, 4.2349e-01, 1.6899e-02, 2.2089e-01],
        [9.5354e-01, 7.0640e-01, 1.6288e-01, 8.9020e-01, 5.1627e-01, 3.5885e-02,
         6.4763e-01, 3.4303e-01, 3.1824e-01, 5.2609e-01, 4.4659e-02, 5.1235e-01,
         9.0508e-01, 5.9886e-01, 4.4500e-01, 7.2783e-01, 4.5626e-01, 3.3887e-01,
         6.2115e-01, 5.5302e-01, 6.8960e-01, 3.6874e-01, 9.0527e-01, 8.3558e-01,
         3.0390e-01, 6.7262e-01, 5.7396e-01, 9.2329e-01, 9.1781e-01, 7.5903e-01],
        [7.7752e-01, 6.1788e-01, 3.3787e-01, 2.1703e-01, 9.4536e-01, 7.1156e-01,
         1.1574e-01, 6.5736e-01, 3.4515e-01, 4.5344e-02, 9.7976e-01, 5.5479e-01,
         6.8678e-01, 4.920

- CPU time taken for heavy operation like 10000*10000 =
18 sec
- GPU time taken for heavy operation like 10000*10000 = 0.5 sec



In [32]:
x.flatten()

tensor([2.1707e-18, 7.0952e+22, 1.7748e+28, 1.8176e+31, 7.2708e+31, 5.0778e+31,
        3.2608e-12, 1.7728e+28, 7.0367e+22])

In [33]:
x

tensor([[2.1707e-18, 7.0952e+22, 1.7748e+28],
        [1.8176e+31, 7.2708e+31, 5.0778e+31],
        [3.2608e-12, 1.7728e+28, 7.0367e+22]])

## Squeeze fn

In [34]:
c = torch.rand(226,226,3)

In [37]:
c

tensor([[[0.7414, 0.3562, 0.8671],
         [0.3627, 0.6940, 0.4759],
         [0.2856, 0.6258, 0.3367],
         ...,
         [0.2251, 0.4714, 0.2725],
         [0.5466, 0.7515, 0.5429],
         [0.7872, 0.6731, 0.7982]],

        [[0.8619, 0.8791, 0.4720],
         [0.6193, 0.5976, 0.5374],
         [0.0408, 0.1637, 0.7557],
         ...,
         [0.5069, 0.9384, 0.6712],
         [0.9680, 0.0315, 0.0370],
         [0.9342, 0.2756, 0.7495]],

        [[0.1521, 0.8253, 0.1846],
         [0.8361, 0.8691, 0.7554],
         [0.6067, 0.6699, 0.2419],
         ...,
         [0.3031, 0.1857, 0.9195],
         [0.3051, 0.4696, 0.3403],
         [0.4297, 0.8070, 0.7251]],

        ...,

        [[0.5298, 0.6694, 0.8371],
         [0.5522, 0.7093, 0.2151],
         [0.8967, 0.5102, 0.2078],
         ...,
         [0.7262, 0.8430, 0.6629],
         [0.3306, 0.9358, 0.1642],
         [0.3661, 0.0386, 0.5751]],

        [[0.1908, 0.2047, 0.0400],
         [0.7989, 0.7538, 0.5627],
         [0.

In [36]:
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])